# Generated by Django 3.2.12 on 2022-04-28 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(choices=[('GRAMS', 'g'), ('TABLESPOONS', 'tbsp'), ('TEASPOONS', 'tsp'), ('MILILITRES', 'ml'), ('N/A', '')], default='N/A', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsInFridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.ingredients'),
            preserve_default=False,
        ),
    ]
