# Generated by Django 3.2.12 on 2022-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220428_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='linkToInstructions',
            field=models.CharField(default='Link not available', max_length=50),
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(related_name='included_in', to='api.Ingredients'),
        ),
    ]
