# Generated by Django 3.2.12 on 2022-05-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220501_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='unit',
        ),
        migrations.AddField(
            model_name='fridge',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fridge',
            name='unit',
            field=models.CharField(choices=[('GRAMS', 'g'), ('TABLESPOONS', 'tbsp'), ('TEASPOONS', 'tsp'), ('MILILITRES', 'ml'), ('N/A', '')], default='N/A', max_length=12),
        ),
    ]
